version: 2.1
jobs:
  build:
    docker:
      - image: python:3-alpine3.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          ame: install dependencies
          command: |
            pwd
            make setup
            make install
      - save_cache:
          key: v1-dependencies-{{ checksum "~/requirements.txt" }}
          paths:
            - ~/.venv
      - run:
          name: run lint
          command: |
            . ~/.venv/bin/activate
            make lint 
workflows:
  default:
    jobs:
      - build