version: 2.1
jobs:
  build:
    docker:
      - image: python:3.9-alpine
    steps:
      - run: 
          name:  Install dependencies
          command: |
            apk add make tar git gcc wget
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/requirements.txt" }}which
          # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Prepare environment
          command: |
            make setup
            make install
      - save_cache:
          key: v1-dependencies-{{ checksum "~/requirements.txt" }}
          paths:
            - ~/.venv
      - run:
          name: Run lint
          command: |
            make lint 
workflows:
  default:
    jobs:
      - build