apiVersion: apps/v1
kind: Deployment
metadata:
  name: catgifs-dev
  namespace: default
spec:
  selector:
    matchLabels:
      run: workflowid
      env: dev
  replicas: 1
  template:
    metadata:
      labels:
        run: workflowid
        env: dev
    spec:
      containers:
      - name: catgifs-dev
        image: imageid
        ports:
        - containerPort: 3000